[package]
name = "kuri_uninstaller"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12", features = ["tokio"] }
winreg = "0.52"
tokio = { version = "1", features = ["full"] }
walkdir = "2"
trash = "3"
dirs = "5.0"
chrono = "0.4"
is_elevated = "0.1.2"
